import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#42f4ce',
    primaryColorHover: '#63f5d3',
    primaryColorPressed: '#38d4b3',
    primaryColorSuppl: '#7cf7d8',
    successColor: '#61f07c',
    successColorHover: '#76f28a',
    successColorPressed: '#53d06b',
    successColorSuppl: '#89f498',
    warningColor: '#f7b83e',
    warningColorHover: '#f8bf59',
    warningColorPressed: '#d79f34',
    warningColorSuppl: '#f9c770',
    errorColor: '#f53d3e',
    errorColorHover: '#f95853',
    errorColorPressed: '#d53435',
    errorColorSuppl: '#fd6e66',

    textColorBase: 'rgba(255, 255, 255, 1)',
    textColor1: 'rgba(255, 255, 255, 0.7)',
    textColor2: 'rgba(255, 255, 255, 0.5)',
    textColor3: 'rgba(255, 255, 255, 0.3)',
    textColorDisabled: 'rgba(255, 255, 255, 0.1)',
  },
  Typography: {
    textColor: 'var(--color-font)',
    textColor1Depth: 'var(--color-font-70)',
    textColor2Depth: 'var(--color-font-50)',
    textColor3Depth: 'var(--color-font-30)',
  },
  Button: {
    textColor: 'var(--color-invert)',
    textColorHover: 'var(--color-invert-80)',
    textColorFocus: 'var(--color-invert-80)',
    textColorPressed: 'var(--color-invert-50)',
    textColorDisabled: 'var(--color-invert-30)',
    textColorTextDisabledPrimary: 'var(--color-primary-80)',
    opacityDisabled: '0.8',
  },
  Input: {
    textColor: 'var(--color-font)',
    caretColor: 'var(--color-font)',
    color: 'transparent',
    colorFocus: 'transparent',
    paddingTiny: '0',
    paddingSmall: '0',
    paddingMedium: '0',
    paddingLarge: '0',
  },
  Checkbox: {
    color: 'transparent',
    colorChecked: 'var(--color-primary)',
    colorDisabled: 'transparent',
    colorDisabledChecked: 'var(--color-primary-50)',
    textColor: 'var(--color-font-70)',
    textColorDisabled: 'var(--color-font-30)',
    border: `1px solid var(--color-primary)`,
    borderChecked: `1px solid var(--color-primary)`,
    borderDisabled: `1px solid var(--color-primary-50)`,
    borderDisabledChecked: `1px solid var(--color-primary-50)`,
    boxShadowFocus: 'none',
  },
  Radio: {
    color: 'transparent',
    boxShadow: `inset 0 0 0 1px var(--color-primary)`,
  },
  Popselect: {
    peers: {
      InternalSelectMenu: {
        optionTextColor: 'var(--color-font)',
        color: 'var(--color-container)',
        optionColorActivePending: 'color-mix(in oklch, var(--color-card) 60%, transparent)',
        optionColorPending: 'color-mix(in oklch, var(--color-card) 60%, transparent)',
      },
    },
  },
  Notification: {
    color: 'var(--color-dialog)',
    borderRadius: 'var(--radius-lg)',
    titleFontSize: 'var(--text-sm)',
    fontSize: 'var(--text-xs)',
    headerTextColor: 'var(--color-font)',
    textColor: 'var(--color-font)',
  },
  Message: {
    color: 'var(--color-dialog)',
    colorInfo: 'var(--color-dialog)',
    colorSuccess: 'var(--color-dialog)',
    colorWarning: 'var(--color-dialog)',
    colorError: 'var(--color-dialog)',
    borderRadius: 'var(--radius-lg)',
    titleFontSize: 'var(--text-sm)',
    fontSize: 'var(--text-xs)',
    textColor: 'var(--color-font)',
    textColorInfo: 'var(--color-font)',
    textColorSuccess: 'var(--color-font)',
    textColorWarning: 'var(--color-font)',
    textColorError: 'var(--color-font)',
  },
  Slider: {
    railColor: 'var(--color-primary-20)',
    railColorHover: 'var(--color-primary-20)',
    railHeight: 'calc(var(--spacing)/2)',
    handleSize: 'calc(var(--spacing)*3)',
  },
  Divider: {
    color: 'var(--color-divider)',
  },
  Scrollbar: {
    color: 'var(--color-primary-40)',
    colorHover: 'var(--color-primary-50)',
  },
  Progress: {
    fillColor: 'linear-gradient(256deg, #e7e368 0%, #41f5cf 100%)',
    railColor: 'var(--color-card)',
  },
}
